### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by suho** [huangshan-ios/Nimble-Code-Challenge#24]
Hello Son 👋 , thank you for your effort on the code submission. I am Su, Senior Software Developer at Nimble, and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions and thus I will create issues where I think there could be more improvements regarding your performance here.

At the same time, please keep in mind that this is a bi-directional process and I would love to hear back from you as well. Therefore, don’t hesitate to raise your questions or share your opinions about the implementation (if any) during the process.

If we are aligned on any issue here and you’d like to correct them, please address the issue using a proper git-flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready) and I will follow up on those fixes. Please note that you don't have to close any of my created issues after merging your PRs, I will help verify and close them for you once they pass. 😇

We expect the code review process to be completed within 2-3 days at most. As a result, ensure you are responsive during this process. If you need additional time, please inform us right away so that we can plan accordingly.

In the end, I really do hope that you find the process enjoyable. Good luck and happy coding. 🤘

**Comment by huangshan-ios** [comment]
Hi @suho , Thank you for notifying me about the reviewing process. I'll follow up on your comments/issues and will check it asap.

**Comment by suho** [comment]
Hello @huangshan-ios again 👋, I complete my review round at the moment. Please go ahead and provide your feedback on all my proposed issues.

You would have the next 1-2 days to resolve the issues then I will finalize my review on your submission 🚀

Have a great afternoon! 🤓

**Comment by huangshan-ios** [comment]
Hi @suho, I'll try to answer all of your questions first. For the [Feature] and [Bug] I'll do it later today. 

anw, thank you for your effort :bow:

**Comment by huangshan-ios** [comment]
I think I have done all the issues, thank @suho  for the reviewing process and some hints. Sorry for the late reply and for resolving the issue, I'm too busy this time so I can not spend all of my time doing this.

**Comment by suho** [comment]
Good afternoon @huangshan-ios 

Thank you for your timely updates on the issues! My review for this code challenge session reaches a conclusion and thus no more submissions will be needed from your end. For the next step, you will be hearing from the Talent Acquisition team about the decision as soon as possible. 🙏

In the end, it was a good pleasure reviewing your code and getting to know you, you have performed well. I wish you all the very best. 🍀

**Comment by suho** [comment]
Note that today is Friday, so you will be hearing from the Talent Acquisition team next week.

Have a nice weekend!
