### ISSUE TITLE
[Question] UI Testing and 3rd-party libraries knowledge concerns 

### ISSUE THREAD

**Issue by suho** [huangshan-ios/Nimble-Code-Challenge#25]
I noticed that you have written the unit tests for the application with a great code coverage percentage. 

At the same time, there are no UI tests found in the application. I am wondering if you ever have had the opportunity to write UI tests before? 
If yes, it would be great if you can demonstrate your skills with a simple UI test to verify some basic UI flows in the application. An example could be the flow to open the Home screen from the Login screen.

Furthermore, I would like to know if you have any experience in any other 3rd-party library for writing unit tests apart from the native XCTest? 
If yes can you tell me a little bit more about how you would write tests using those libraries?

**Comment by huangshan-ios** [comment]
Hi @suho, 
Thanks for your question.

I usually use an automation framework like Appium to test the UI so I don't have too much experience in UI test with XCTest.

I also use Quick/Nimble & [RxNimble](https://github.com/RxSwiftCommunity/RxNimble) for the unit test.

For the test with RxNimble, I just use it to provide a more readable, detailedly context of testing and easy expected results. 

As you can see in the UT with RxBlock and RxTest, the coding is too long and complex, if we use RxNimble, we can reduce some of these steps and also provide more context about the UT.

**Comment by suho** [comment]
Hi @huangshan-ios, it's great to know that you have experience with Quick/Nimble and RxNimble. All good from my side.
