### ISSUE TITLE
[Question] Hardcode ClientID and ClientSecret

### ISSUE THREAD

**Issue by suho** [huangshan-ios/Nimble-Code-Challenge#26]
Currently, you are hardcoding the `client_id` and `client_secret`  in the code and using them in different places (login, refresh token) without defining constants for that. Do you have another approach to handling the `client_id` and `client_secret` in different places?

On the other hand, client_id and client_secret are sensitive information, they are not configured for different environments (staging, production), do you know any best practices to handle this situation?

**Comment by huangshan-ios** [comment]
Oh, I forgot this one when setting up the configuration of the Release and Debug scheme. (We can assume that is the staging, production).

I think for this, we can move the `client_id` and the `client_secret` to the .xcconfig file to separate the configuration of each scheme/environment.

And with this approach, we also can easily change it (if needed) in the CI/CD when running the pipeline.

I'll make a pull request to move it into the .xcconfig

**Comment by suho** [comment]
@huangshan-ios All good with this approach 👍. I think we can close this issue
