### ISSUE TITLE
[Bug] The shimmer loading indicator's animation doesn't look identical to the design

### ISSUE THREAD

**Issue by suho** [huangshan-ios/Nimble-Code-Challenge#28]
## Issue

The application needs to show the initial shimmer loading view with animation after first entering the app with a valid logged-in session. Currently, the loading animation is not matching with the design.

## Expect

The animation for the skeleton loading view must be implemented like the following design

https://user-images.githubusercontent.com/19943832/177250662-30f9d552-9f63-4778-8a17-3ca5a23f5cc6.mov

## Steps to reproduce

1. Open the application with a previously logged-in session
2. Check the loading indicator on the home screen.

https://user-images.githubusercontent.com/19943832/177250833-949ba118-31bd-4bff-9a62-c03ceeb38b6a.mp4

**Comment by huangshan-ios** [comment]
Hi @suho , and this too.

**Comment by suho** [comment]
@huangshan-ios Got it, I will take a look at the implementation

**Comment by suho** [comment]
All good with this issue
