### ISSUE TITLE
[Bug] The survey images are difficult to see on the Home screen

### ISSUE THREAD

**Issue by suho** [huangshan-ios/Nimble-Code-Challenge#29]
## Issue

Currently, the survey images are small to display in full-screen on the Home screen. Could you help me to check if we can improve the quality of the image?

<img src="https://user-images.githubusercontent.com/19943832/177252308-457d570c-82d7-4273-a257-14c0fba99f4e.png" width="200" />

## Expected

The user can use good-quality images on the Home screen

**Comment by huangshan-ios** [comment]
Hi @suho , I don't have too much experience in this part, but I've read this article:
https://medium.com/ymedialabs-innovation/resizing-techniques-and-image-quality-that-every-ios-developer-should-know-e061f33f7aba

But still, with this article, our image response still can not be of good quality. I'll create a PR implemented this solution for you to check.

**Comment by suho** [comment]
@huangshan-ios Technically, you don't need to resize the image with `Accelerate`. A hint to get the high-resolution of an image: "Check again the API document" 🤓

**Comment by huangshan-ios** [comment]
Hi @suho , Thanks for the hint <3. I've updated the PR and merged please check it.
