### ISSUE TITLE
[Question] Fastlane knowledge concerns

### ISSUE THREAD

**Issue by suho** [huangshan-ios/Nimble-Code-Challenge#31]
From Nimble technical requirements, Nimble requires to use `Fastlane` in the project. It seems you didn't use `Fastlane`. I'm wondering if you ever have had the opportunity to use Fastlane? If yes, it would be great if you tell me which use case you are using Fastlane for?

Furthermore, I would like to know if you have any experience in setting up CI/CD for an iOS project? If yes can you tell me a little bit more about how you would set up CI/CD for a new project?

**Comment by huangshan-ios** [comment]
Hi @suho, When I implement the challenge I don't really understand the requirement about Fastlane. 

So I leave it to do later, but I don't have too much time to do it then it's still not implemented. I'll try to implement it with some easy cases.

And for your question about the CI/CD, I've experience setup CI/CD with BitRise in my previous project but I don't really remember too much about it.

That is the first project that I build from scratch, in some of the previous projects I only maintain the CI/CD with Jenkins, TeamCity, and CircleCI...

For the project that uses BitRise, I set up the pipelines to:

1. Check if the pull request is valid.
2. Trigger `main` to build the `staging` version if the version tag is increased and push the IPA to TestFlight.
3. A pipeline to build a `production` version but only can trigger manually and if the version tag is larger than the previous.

All of these pipelines will include some steps:
1. Clean the project
2. Install Cocoapods
3. Check code lint (swiftlint)
4. Check the pod lint (Fastlane action, as I remember it is pod_lib_lint)
5. Run Unit test
6. Increase build version if needed (only for the staging and production pipeline)

**Comment by suho** [comment]
Hi @huangshan-ios, good to know that you have experience with Bitrise and CI/CD tools. Moreover, your implementation with Fastlane is good enough for this challenge 👍
