### ISSUE TITLE
[Question] Approach to handle retry when the token is expired

### ISSUE THREAD

**Issue by suho** [huangshan-ios/Nimble-Code-Challenge#33]
Currently, you are using `retry` from `RxSwift` to handle when the token is expired. Given a project that doesn't use `RxSwift` or `Moya` (under the hood, it's using Alamofire), but it uses `Alamofire` only, I'm wondering how can you implement the retry feature?

Note: You don't need to update the code, just tell me the approach 🙏

**Comment by huangshan-ios** [comment]
If we only use Alamofire, we can custom Alamofire `RequestInterceptor` to check/retry the request if needed.

It will provide `RequestAdapter` `RequestRetrier` protocol with 2 functions `adapt` and `retry` to retry a request if needed.

We can send the default header parameter (or anything else...) with the `adapt` function and can check/retry the new one with the `retry` function.

**Comment by suho** [comment]
Your approach is good in case the project is using only `Alamofire` 👍. We can close this issue now.
